# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/inelos/projects/KG/watchdog/../ui/lab_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 681)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 17))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 15))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.linesCount = QtWidgets.QLabel(Form)
        self.linesCount.setMinimumSize(QtCore.QSize(50, 0))
        self.linesCount.setMaximumSize(QtCore.QSize(50, 17))
        self.linesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.linesCount.setObjectName("linesCount")
        self.horizontalLayout.addWidget(self.linesCount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setMaximumSize(QtCore.QSize(150, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.horizontalSlider_2.setMinimum(50)
        self.horizontalSlider_2.setMaximum(150)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.linesLength = QtWidgets.QLabel(Form)
        self.linesLength.setMinimumSize(QtCore.QSize(50, 0))
        self.linesLength.setMaximumSize(QtCore.QSize(50, 17))
        self.linesLength.setAlignment(QtCore.Qt.AlignCenter)
        self.linesLength.setObjectName("linesLength")
        self.horizontalLayout_4.addWidget(self.linesLength)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.generateLinesButton = QtWidgets.QPushButton(Form)
        self.generateLinesButton.setObjectName("generateLinesButton")
        self.verticalLayout.addWidget(self.generateLinesButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.moc_drawArea = QtWidgets.QWidget(Form)
        self.moc_drawArea.setMinimumSize(QtCore.QSize(550, 550))
        self.moc_drawArea.setObjectName("moc_drawArea")
        self.horizontalLayout_3.addWidget(self.moc_drawArea)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Количество отрезков"))
        self.linesCount.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Длина отрезков (макс.)"))
        self.linesLength.setText(_translate("Form", "50px"))
        self.generateLinesButton.setText(_translate("Form", "Пересоздать набор отрезков"))
